### PR TITLE
[fix]: default value of inspector-pp-max-width and inspector-pp-use-m…

### PR DESCRIPTION
**Pull request by nhannht**
- Thank for the very nice package.
- If you don't want to fix the small issue as I suggest. I think you should add more info to README.
- Example
```elisp
;; With use-package or use-package! if use Doom Emacs
(use-package! inspector
  :init
  (setq inspector-pp-use-max-width t)
  (setq inspector-pp-max-width "window width")
  )
```

Another issue I think you should change.
Cannot insert directly with tree-inspector package from elpa. You should inform normal user config their package management load tree-inspector.el
Example with Doom emacs package manager
```elisp
(package! tree-inspector
  :recipe (:host github :repo "mmontone/emacs-inspector/"
                 :files ("tree-inspector.el")))
```

Finally for some reason my Emacs not auto-install treeview package even `require 'treeview` in the source code, maybe should add this line in use-package
```elisp
(use-package tree-inspector
  :after '(treeview) )
```

### CODE REVIEW

**Comment by mmontone** [comment]
Hello. Thanks for the PR. Didn't know about the pp package not being loaded. 

As an alternative, how about checking with featurep? : `(if (featurep 'pp) pp-max-width "window-width"))`. ?

**Comment by mmontone** [comment]
I don't use `use-package` and `use-package!`, I just install from `package-list-packages`. That's why I haven't included more docs with that.

**Comment by nhannht** [comment]
Sorry, this is the first time I pr to other Emacs-related package and Doom-related package, I need to recheck some technical details. I will close this PR and replace it with better later.

**Comment by mmontone** [comment]
Your code is not bad. In fact, that code you touched is new and is very possible that is not working well for all Emacs distros. I've been lazy an only tested for v29.1. I'll apply some changes. Don't hesitate to open another one, you could open another one clarifying the docs README perhaps.

**Pull request closed without merging**
